// <auto-generated />
namespace Qorder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QOR0009 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QOR0009));
        
        string IMigrationMetadata.Id
        {
            get { return "202106210537065_QOR-0009"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
